### ISSUE TITLE
Add Mercator or set DOMAIN_CURRENT_SITE

### ISSUE THREAD

**Issue by roborourke** [humanmade/platform-cms#11]
As we're going multisite by default this constant needs to be set. Otherwise we can get Mercator v2 finished off and use that as a built in. The Mercator v2 GUI isn't completed yet but it's maybe a days work off.

**Comment by joehoyle** [comment]
What do we need this constant for specifically?

**Comment by roborourke** [comment]
Sorry, WP CLI complains about it not being set, but it's ok if you supply `--url`

**Comment by joehoyle** [comment]
Ohh gotcha! Is there any way we could not define this in code, and instead lookup the primary blog URL, and default to that? It always seemed a bit odd how you needed to define this in code.

**Comment by rmccue** [comment]
It’s better generally to avoid setting this, as it breaks multinetwork if anyone wants to do that.

**Comment by roborourke** [comment]
Ok cool. Any thoughts on the Mercator idea?

**Comment by joehoyle** [comment]
I don't know that mercator is really a common requested part of multisite. Now you can just run sites on different domains natively, the need for site aliases is a lot more niche IMO.

**Comment by roborourke** [comment]
👍 closing this one, no further action required.
