### ISSUE TITLE
Ensure WP_HOME is using https

### ISSUE THREAD

**Issue by roborourke** [humanmade/platform-cms#16]
It's a bit mysterious how WP handles the `home` and `siteurl` options but the issue I'm seeing is that even though I'm browsing via the `https` URL some functions still get the `http` version of the URL from the database. This is probably because I didn't specify the scheme in the URL at the time I ran `wp core multisite-install`.

We should add a way to enforce SSL URLs all the time through code rather than rely on the db ever. Notable case was that the block editor was totally broken as `get_rest_url()` returned `http`.

**Comment by joehoyle** [comment]
@roborourke this sounds like a config issue that you had the site installed under http, not https. I think that should now be resolved, and was a legacy problem from coming from hmdocker?

**Comment by roborourke** [comment]
No this was with altis.dev but I maybe didn't have the latest version of the CMS module. The WP CLI command I ran was `wp core multisite-install --url=hm-platform-new.altis.dev`. I guess it just infers `http://` during the install process

**Comment by joehoyle** [comment]
Ahh yeah that would do it. We might be able to fix that, but also when you run `composer local-server cli` it will pass `https://hm-platform.altis.dev`

**Comment by roborourke** [comment]
Yep. If the install step can be automated that would do the trick. Maybe we should define `WP_SITEURL` as well

**Comment by joehoyle** [comment]
`WP_SITEURL` is ignored on multisite though!

**Comment by roborourke** [comment]
🤦‍♂️Will close this issue. Can make a more specific issue re. doing the install. If the cli command helper passes the URL then that should solve it.
