### ISSUE TITLE
Include built in themes in wp-config.php

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/platform-cms#20]
The default install of this module can lead to a WSOD or error message if a theme is not active. it would be helpful to include the default themes in the config, similar to this technique:

```php
// =======================
// Use built-in themes too
// =======================
if ( empty( $GLOBALS['wp_theme_directories'] ) ) {
	$GLOBALS['wp_theme_directories'] = array();
}
if ( file_exists( WP_CONTENT_DIR . '/themes' ) ) {
	$GLOBALS['wp_theme_directories'][] = WP_CONTENT_DIR . '/themes';
}
$GLOBALS['wp_theme_directories'][] = ABSPATH . 'wp-content/themes';
$GLOBALS['wp_theme_directories'][] = ABSPATH . 'wp-content/themes';
```

**Comment by roborourke** [comment]
@peterwilsoncc Ryan just merged a PR for adding a basic splash page if there's no theme to avoid this problem, see #13 

I'm not sure we want to specifically include the default WP themes, better to only show the ones that are part of a client's project but open to discussion & feedback there if you feel there's a compelling reason that hasn't come up. In addition there's going to be a basic theme in the humanmade/platform-skeleton#1 repo which new projects will be bootstrapped from.

**Comment by rmccue** [comment]
Agreed, I'd rather we not include the default themes out-of-the-box.

**Comment by peterwilsoncc** [comment]
OK, the default theme on the site I was building hadn't been network enabled so I hit some weirdness but humanmade/platform-cms#14 will help with that.
